# Generated by Django 3.2.5 on 2022-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='pics')),
                ('date', models.DateTimeField()),
                ('headline', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
